# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isPrime <- function(n) {
    .Call(`_rprimes_isPrime`, n)
}

nthPrime <- function(n) {
    .Call(`_rprimes_nthPrime`, n)
}

genPrimes <- function(max) {
    .Call(`_rprimes_genPrimes`, max)
}

